#/appspec.yml
version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/deplpy-test
hooks:
  BeforeInstall:
    - location: /home/ubuntu/deplpy-test/scripts/before_install.sh
      timeout: 180
      runas: root
  ApplicationStart:
    - location: /home/ubuntu/deplpy-test/scripts/application_start.sh
      timeout: 180
      runas: root
