# appspec.yml
version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/deplpy-test
hooks:
  BeforeInstall:
    - location: /scripts/before_install.sh
      timeout: 180
      runas: ec2-user
  ApplicationStart:
    - location: /scripts/application_start.sh
      timeout: 180
      runas: ec2-user
